/**
 * React Native entry point — registers the root component with the
 * native app shell (ios/ and android/, generated by the RN CLI).
 *
 * The `webrtcGlobals` side-effect import MUST run before any sip.js
 * module loads — it installs `react-native-webrtc`'s primitives as
 * the globals that sip.js's bundled platform/web SDH expects (see
 * src/sip/webrtcGlobals.ts).
 */
import './src/sip/webrtcGlobals';

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
