/**
 * React Native entry point — registers the root component with the
 * native app shell (ios/ and android/, generated by the RN CLI).
 */
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
